/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testPackage;

import AppPackage.AnimationClass;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Phil Rey Paderogao
 */
public class animationWindow extends javax.swing.JFrame {

    AnimationClass anim;
    animationThread animator;
    public animationWindow() {
        anim = new AnimationClass();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        card1 = new javax.swing.JLabel();
        card2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        card.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testPackage/Card Example.jpg"))); // NOI18N
        card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cardMouseEntered(evt);
            }
        });
        getContentPane().add(card);
        card.setBounds(160, 30, 110, 140);

        jButton1.setText("Slide Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 420, 100, 23);

        jButton2.setText("Slide In");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 420, 67, 23);

        card1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testPackage/Card Example.jpg"))); // NOI18N
        getContentPane().add(card1);
        card1.setBounds(280, 30, 110, 140);

        card2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testPackage/Card Example.jpg"))); // NOI18N
        getContentPane().add(card2);
        card2.setBounds(400, 30, 110, 140);

        setSize(new java.awt.Dimension(631, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(animator != null){
            if(animator.isDone() && animator.getProgress() == 100){
                movingFormsClass [] animations = {
                    new movingFormsClass(card.getX(),card.getX()-350, 2, 1, card,3),
                    new movingFormsClass(card1.getX(),card1.getX()-350, 2, 1, card1,3),
                    new movingFormsClass(card2.getX(),card2.getX()-350, 2, 1, card2,3),
                };
                
                animator = new animationThread(animations, 40);
                animator.execute();
            }else{
                System.err.println("No Done yet. Press again later");
            }
        }else{
            movingFormsClass [] animations = {
                new movingFormsClass(card.getX(),card.getX()-350, 2, 1, card,3),
                new movingFormsClass(card1.getX(),card1.getX()-350, 2, 1, card1,3),
                new movingFormsClass(card2.getX(),card2.getX()-350, 2, 1, card2,3),
            };

            animator = new animationThread(animations, 40);
            animator.execute();
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(animator != null){
            if(animator.isDone() && animator.getProgress() == 100){
                movingFormsClass [] animations = {
                    new movingFormsClass(card2.getX(),card2.getX()+350, 2, 1, card2,4),
                    new movingFormsClass(card1.getX(),card1.getX()+350, 2, 1, card1,4),
                    new movingFormsClass(card.getX(),card.getX()+350, 2, 1, card,4),
                };
                
                animator = new animationThread(animations, 40);
                animator.execute();
            }else{
                System.err.println("No Done yet. Press again later");
            }
        }else{
            movingFormsClass [] animations = {
                new movingFormsClass(card2.getX(),card2.getX()+350, 2, 1, card2,4),
                new movingFormsClass(card1.getX(),card1.getX()+350, 2, 1, card1,4),
                new movingFormsClass(card.getX(),card.getX()+350, 2, 1, card,4),
            };

            animator = new animationThread(animations, 40);
            animator.execute();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardMouseEntered
        card.setVisible(false);
        card.setIcon(rescaleImage(new ImageIcon("Card Example.jpg"), 100, 50));
        card.setVisible(true);
    }//GEN-LAST:event_cardMouseEntered
    
    private ImageIcon rescaleImage(ImageIcon image,int width,int hieght){
        Image img = image.getImage();
        Image newImg = img.getScaledInstance(width, hieght, Image.SCALE_SMOOTH);
        ImageIcon imageToSend = new ImageIcon(newImg);
        return imageToSend;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(animationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(animationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(animationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(animationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new animationWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel card;
    private javax.swing.JLabel card1;
    private javax.swing.JLabel card2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
